sudo: false
language: ruby
rvm:
  - 2.5.1

before_install:
  - gem install bundler -v 2.0.1

script:
  - "spec/dummy/bin/setup"

notifications:
  slack: fadendaten:tWoet2mtObvbwSZSyUAY93jl
  email: false
